name: ${{ github.event_name == 'push' && 'Build and Push to Docker Hub' || (github.event.client_payload.trigger_type == 'auto' && 'Auto-build' || 'Manual-build') }}

on:
  push:
    branches:
      [ main ]
    paths:
      - '**'
  repository_dispatch:
    types: [docker-build]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # 任务名称简化为三种情况
    name: ${{ github.event_name == 'push' && 'Build and Push' || (github.event.client_payload.trigger_type == 'auto' && 'Auto-build' || 'Manual-build') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Trigger Source
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "This build was triggered by a push to main branch"
          elif [ "${{ github.event.client_payload.trigger_type }}" = "auto" ]; then
            echo "Auto-build: src update on ${{ github.event.client_payload.timestamp }}"
          elif [ "${{ github.event.client_payload.trigger_type }}" = "manual" ]; then
            echo "Manual-build: dispatched on ${{ github.event.client_payload.timestamp }}"
          else
            echo "Unknown trigger source"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pandoc-api:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/pandoc-api:latest
